import { NextFunction, ParamsDictionary } from "express-serve-static-core";
import { Request, Response } from "express";
import { HTTP_STATUS } from "~/constants/httpStatus";
import scoreService from "~/services/score.service";

// export const create = async (req: Request<ParamsDictionary, any, any>, res: Response, next: NextFunction) => {
//     const userId = req.userId as string;
//     try {
//         const filePath = req.file?.path ?? null;
//         const result = await scoreService.handleScoreRawData(userId, filePath);
//         return res.status(HTTP_STATUS.OK).json({
//             message: "Đã xử lý dữ liệu thành công!",
//             result,
//         });
//     } catch (error) {
//         return next(error);
//     }
// };
export const create_round2 = async (req: Request<ParamsDictionary, any, any>, res: Response, next: NextFunction) => {
    const userId = req.userId as string;
    try {
        const filePath = req.file?.path ?? null;
        const result = await scoreService.handleScoreRawData(userId, filePath);
        return res.status(HTTP_STATUS.OK).json({
            message: "Đã xử lý dữ liệu thành công cho round 2!",
            result,
        });
    } catch (error) {
        return next(error);
    }
};

// const firstSubmit = [
//     "https://drive.google.com/file/d/1BtUwi0CP-QS1J4UtWmvUnObNtI-UK1ku/view?usp=drivesdk",
//     "https://drive.google.com/file/d/1hcnbSBF2sSWAIfQfNEwA6SELTh3Xkd1l/view?usp=drivesdk",
//     "https://drive.google.com/file/d/1OBtwgUHm7lNddbZTbgasrhyzJ8dcJyKr/view?usp=drivesdk",
//     "https://drive.google.com/file/d/1Jq8JD27Ruk8HdFnCelp3mvuDqgYl5w9z/view?usp=drivesdk",
//     "https://drive.google.com/file/d/1Pa1CNYwOSTkUj0GwKMiEm65fJ4L_52j0/view?usp=drivesdk",
//     "https://drive.google.com/file/d/1uji9IHRJo9h7pnSXHaQICMykcSTl8Gic/view?usp=drivesdk",
//     "https://drive.google.com/file/d/1wTBUdxY4mqGY8KvG9GqL9cUu5f0hdgGh/view?usp=drivesdk",
//     "https://drive.google.com/file/d/13vXx2MUddB6TRuM7zKVVcRZHNSiUeZNZ/view?usp=drivesdk",
//     "https://drive.google.com/file/d/194Jb9Md-SX0bfDZwxVFg2Yod7mwqzxh2/view?usp=drivesdk",
//     "https://drive.google.com/file/d/12VOXYlX0dSq6abUAC6Q5-TWGAsGV27yB/view?usp=drivesdk",
//     "https://drive.google.com/file/d/1V1_mr0VMLnwMrdJVmfMXMnizhB9__ipz/view?usp=drivesdk",
//     "https://drive.google.com/file/d/1WTQesK8qGI3RpKKsUYbRuI4mQmyff-7t/view?usp=drivesdk",
//     "https://drive.google.com/file/d/1nLLhndochw_-EIf7vWdGFK6l9tMspz5h/view?usp=drivesdk",
//     "https://drive.google.com/file/d/1QTut47Dft7VaeLS3at1YN8WjqvqdjP7x/view?usp=drivesdk",
//     "https://drive.google.com/file/d/1PSK4afyJ3eVPQT9ZWyl67RXnHiqZPk9Y/view?usp=drivesdk",
//     "https://drive.google.com/file/d/1-t1chfcE9TxKiS06nWiQB-okDUUutE1-/view?usp=drivesdk",
//     "https://drive.google.com/file/d/17Cno6ETUEM0Aeq1Kg3iT1R7dUknQsYnS/view?usp=drivesdk",
//     "https://drive.google.com/file/d/1NC6eLr0YX3sI_bTGam_-0LX-w4Yi0Vko/view?usp=drivesdk",
//     "https://drive.google.com/file/d/1sTXa9G6-pJDE0oYLbR27Qq1MzQIz-3Lg/view?usp=drivesdk",
//     "https://drive.google.com/file/d/1_zbojzt5mm2fkXS8lvjsBnpSunWJ-Eel/view?usp=drivesdk",
//     "https://drive.google.com/file/d/1DY4RMLgDdz-d6MKREn5QHm2vRR9fo_y9/view?usp=drivesdk",
//     "https://drive.google.com/file/d/14WfQ-xkSxb7qiUQ-3f1nutTf3JG_bQVX/view?usp=drivesdk",
//     "https://drive.google.com/file/d/1y91MiHS-b9vHxWw9BXpcSz1LH0VAWbEd/view?usp=drivesdk",
//     "https://drive.google.com/file/d/1dLYCwz49jK1Dy7D-ZuAaPzidpgO7Sac7/view?usp=drivesdk",
//     "https://drive.google.com/file/d/1aFTBScQuE3fdPUQx8Do9xcm4uNK7uv0x/view?usp=drivesdk",
//     "https://drive.google.com/file/d/1MBJ5MA6aUeLMI-sQdHsrSVk9wwFQNgte/view?usp=drivesdk",
//     "https://drive.google.com/file/d/1kfDGpVBCz3ncAObf_RNj8W4PP4UufTDx/view?usp=drivesdk",
//     "https://drive.google.com/file/d/1yrNzA7kITMMOLmUbyWuMX6kcPLXlg84j/view?usp=drivesdk",
//     "https://drive.google.com/file/d/1q-prPuPchTmyPnrE6chwlDeqQbIcz9Yc/view?usp=drivesdk",
//     "https://drive.google.com/file/d/1hJvEe7Q14vgGf8Pn3GJRs5hTb2g2jnP3/view?usp=drivesdk",
//     "https://drive.google.com/file/d/1wtlUee2_wy7ZPeGSUFo-79e5INmZnyJy/view?usp=drivesdk",
//     "https://drive.google.com/file/d/1C2agruVTsoxVlF0Hn_1oQkKGoAikicSE/view?usp=drivesdk",
//     "https://drive.google.com/file/d/17cYXan2RsVKFaNbAjYEi7kSNxX1aAEDI/view?usp=drivesdk",
//     "https://drive.google.com/file/d/12pDsbCWMOJ7dgIny6Y75hcgthfSpfEUV/view?usp=drivesdk",
//     "https://drive.google.com/file/d/13tG_n6BwGRZ0z4sP5LFkKWO274wGZJOj/view?usp=drivesdk",
//     "https://drive.google.com/file/d/1uUgFK_tsgdXDIHPKk_Qrhv66cUrP9qE5/view?usp=drivesdk",
//     "https://drive.google.com/file/d/1jPToi9Vc6eONCd_ogi5rfVG5kCS0WNZb/view?usp=drivesdk",
//     "https://drive.google.com/file/d/1xZ8FsCRdPInzkCBdwZ3PBVlUr7Trimxo/view?usp=drivesdk",
//     "https://drive.google.com/file/d/1a5CeRsLZmhEP9slrO3AcKjcP5DS4pvrx/view?usp=drivesdk",
//     "https://drive.google.com/file/d/18F3ofnGCbeP3OLNEHECSwUdyh4Q7xYqt/view?usp=drivesdk",
//     "https://drive.google.com/file/d/1p1gKhfHEPPdsDTxLOZUnBPog93VkiBR9/view?usp=drivesdk",
//     "https://drive.google.com/file/d/1pBzN6cB2kgj-mpN-wR5FCbdu290cgcWk/view?usp=drivesdk",
//     "https://drive.google.com/file/d/1fc5GgAY2nHzOEMcJh2bcc5yjC9r6YIZj/view?usp=drivesdk",
//     "https://drive.google.com/file/d/1lzgKje5se9c-yol2vNIik0hRX5-POfxu/view?usp=drivesdk",
//     "https://drive.google.com/file/d/1-RZDKR3F88PEw3os4BPsM-TObyKWsfEl/view?usp=drivesdk",
//     "https://drive.google.com/file/d/1sq0Ay-Wy4R8heWjxgM1WmNt06odBWjec/view?usp=drivesdk",
//     "https://drive.google.com/file/d/1Pb9u7h795w1yL6Vs3s1PTVVeMzrBXDzZ/view?usp=drivesdk",
//     "https://drive.google.com/file/d/11v3lCrH2U9IpNtNpE2giyiBwfWgvB1Lp/view?usp=drivesdk",
//     "https://drive.google.com/file/d/1H_6_zTcRwsVhmiMk6cYCPfihwz8mievt/view?usp=drivesdk",
//     "https://drive.google.com/file/d/1hBY4oCCKFs7wopvdFvciwnCGVfSMtnzq/view?usp=drivesdk",
//     "https://drive.google.com/file/d/1eR9r0OdqRxQ9ozstM8mwT3h1R1pcCbNl/view?usp=drivesdk",
//     "https://drive.google.com/file/d/19x0C8zTQv2MAcbbIeltpmRKkpibrytZH/view?usp=drivesdk",
//     "https://drive.google.com/file/d/1EcjOBpU8gEtq6MpLSKhDOuX94486zM9a/view?usp=drivesdk",
//     "https://drive.google.com/file/d/1rpLXo808D4qQQuUsqjWXeZ_Vk78_04a6/view?usp=drivesdk",
//     "https://drive.google.com/file/d/1nrNEdaLh5g9JGSvm7_bn9dpjBJ0M2jN3/view?usp=drivesdk",
//     "https://drive.google.com/file/d/1IBF_9CUpkwSswothWV4R_25XH1jFcPnU/view?usp=drivesdk",
//     "https://drive.google.com/file/d/18mXLQHnXsoikXzbx6h-S5PVz_EF5XmV5/view?usp=drivesdk",
//     "https://drive.google.com/file/d/1rF0jGC-KXJ07C-0zDRE2ONDVSIdC4x0o/view?usp=drivesdk",
//     "https://drive.google.com/file/d/1NEqm9uJEf5ypcPWvEZXijw7knkuEHqP6/view?usp=drivesdk",
//     "https://drive.google.com/file/d/1k9fuCnD4sdehxDjdSpAUYpIHuSjrjL_4/view?usp=drivesdk",
//     "https://drive.google.com/file/d/1zg5n2Ec3GOEU6RW14UGC_Nei-av988Zr/view?usp=drivesdk",
//     "https://drive.google.com/file/d/1prQVXzBAzAZLcko4LJTlGeHcy6ohYqbD/view?usp=drivesdk",
//     "https://drive.google.com/file/d/1BFqDJi3mjVl_PWEp1QCprrIxA3jmZ--W/view?usp=drivesdk",
//     "https://drive.google.com/file/d/13vogUQoS2AIWk0Ug5t_Y0ZGj_6DkJi3L/view?usp=drivesdk",
//     "https://drive.google.com/file/d/1u9PzSx9VTqdWqipX66tEIY5-xgOb-8_Y/view?usp=drivesdk",
//     "https://drive.google.com/file/d/1eo9zBp8Ep7o0ToN3JrQcC49NVreqtyCE/view?usp=drivesdk",
//     "https://drive.google.com/file/d/1b_50yBzUTz6dsA1IMRqhM4xcIcZ42B54/view?usp=drivesdk",
//     "https://drive.google.com/file/d/1J6DYBuR5zbwB8FsY8cDrAbeegXAkivA7/view?usp=drivesdk",
//     "https://drive.google.com/file/d/1V8FiZLPOQG34BwAVw3mTdkaNsR1qfMtw/view?usp=drivesdk",
//     "https://drive.google.com/file/d/1urzGVueUahjVuisDCDPi1RJGOoi4S3S-/view?usp=drivesdk",
//     "https://drive.google.com/file/d/1WI-MBz0leUpl_MJ4iKfKzThKMTCMIav6/view?usp=drivesdk",
//     "https://drive.google.com/file/d/11ieDInC9nrjGitd-5wPnwDeY3RKDh92N/view?usp=drivesdk",
//     "https://drive.google.com/file/d/1lYLMu1yGI27a-bIOW77RYyiOJjklorjn/view?usp=drivesdk",
//     "https://drive.google.com/file/d/1JkzuQSK8ec0ix-OifHQs4myKJElKm3kI/view?usp=drivesdk",
//     "https://drive.google.com/file/d/1zE7p5b2nSFwA7WJjFHLrN6xiqe-GE1Yz/view?usp=drivesdk",
//     "https://drive.google.com/file/d/1Ie5Z1m_E11Bd0hzffFZ-WNrQVLTQF8BF/view?usp=drivesdk",
//     "https://drive.google.com/file/d/1iz7fmqSypS6vOxz7SHAZtKghPrMD1Kpz/view?usp=drivesdk",
//     "https://drive.google.com/file/d/1_GIdrA8TaD9rOQMwQniEGnT7vijfmj6D/view?usp=drivesdk",
//     "https://drive.google.com/file/d/16dJSEBmhpiuSkWMuCfqvJNURXcq3qBsa/view?usp=drivesdk",
//     "https://drive.google.com/file/d/1qic1jogGGGDS5HSx2LbsTpTRuwzV3u4O/view?usp=drivesdk",
//     "https://drive.google.com/file/d/1wgCUwjMwvuv_iDgAak0My9fugg3qzePd/view?usp=drivesdk",
//     "https://drive.google.com/file/d/1qXxHhAW4eOGryEVXPoIumAlbi9a3hxFK/view?usp=drivesdk",
//     "https://drive.google.com/file/d/1S45794ohfgVGvbJJyxcQmXOxMJC94ets/view?usp=drivesdk",
//     "https://drive.google.com/file/d/1tRaxic9266aYJZRN-oBHXk8D1gpSTXuD/view?usp=drivesdk",
//     "https://drive.google.com/file/d/1pxbWIcsCXSOEJ-nDVuENn9lwJ9B3Le_1/view?usp=drivesdk",
//     "https://drive.google.com/file/d/1OiZ5sGtHOgqsIjpK20HL1XIPqtFFw--z/view?usp=drivesdk",
//     "https://drive.google.com/file/d/1la3DB2f1bH0EL9C0hSF9TDpIjnXxIxfy/view?usp=drivesdk",
//     "https://drive.google.com/file/d/1fWKEOAf3fiavzNm22HplKgzEheXBEwNN/view?usp=drivesdk",
//     "https://drive.google.com/file/d/1wgUgh_nAo369N_AQwBQyfsms_KfUIzYT/view?usp=drivesdk",
//     "https://drive.google.com/file/d/1IvYZEX0R3veAajdjwQHpPQ8s-4Uapk1l/view?usp=drivesdk",
//     "https://drive.google.com/file/d/18TIyzESO-Yl9LonjBwP--rRUnMMXN1cG/view?usp=drivesdk",
//     "https://drive.google.com/file/d/1TFmsSrYtaYDu6EseYTEksJWo8RXsftvx/view?usp=drivesdk",
//     "https://drive.google.com/file/d/11ksUGUXVky5QpYLZAxi6b8qXnX6mpHBJ/view?usp=drivesdk",
//     "https://drive.google.com/file/d/1MR5QhvN2MEhapYFxYj0Eaa0EU4VzGBj-/view?usp=drivesdk",
//     "https://drive.google.com/file/d/179gRy7lGtjZ7LkXQySLJnMUBwp5BL5Rr/view?usp=drivesdk",
//     "https://drive.google.com/file/d/121LXZDnXc7uqdd5Rzp1Tn2dqC6ZKXnw-/view?usp=drivesdk",
//     "https://drive.google.com/file/d/1H-PCpR5hugGo6xtS2ncspzKP4zcsV4w2/view?usp=drivesdk",
//     "https://drive.google.com/file/d/1adM4L3sYBoplBM5xcQbC6ZPKyzbgu0dF/view?usp=drivesdk",
// ];
// const studentCodes = [
//     "SE211156",
//     "SE210795",
//     "SE211351",
//     "SE201591",
//     "SE190210",
//     "SE204913",
//     "SE210043",
//     "SE201404",
//     "SE211866",
//     "SE211377",
//     "SE211591",
//     "SE201566",
//     "SE211135",
//     "SE211556",
//     "SE201011",
//     "SE210130",
//     "SE210835",
//     "SE210117",
//     "SE211470",
//     "SE211960",
//     "SE210741",
//     "SE210905",
//     "SE211201",
//     "SE210666",
//     "SE212092",
//     "SE211962",
//     "SE200441",
//     "SE212275",
//     "SE210756",
//     "SE211899",
//     "SE211611",
//     "SE201018",
//     "SE210452",
//     "SE203367",
//     "SE211731",
//     "SE200932",
//     "SE211601",
//     "SE210318",
//     "SE210946",
//     "SE210810",
//     "SE203055",
//     "SE205177",
//     "SE192363",
//     "SE211888",
//     "SE201183",
//     "SE200972",
//     "SE211755",
//     "SE201843",
//     "SE204111",
//     "SE211766",
//     "SE201619",
//     "SE203690",
//     "SE210918",
//     "SE211093",
//     "SE203677",
//     "SE200516",
//     "SE210364",
//     "SE203555",
//     "SE211449",
//     "SE210777",
//     "SE203237",
//     "SE211968",
//     "SE211947",
//     "SE210773",
//     "SE211898",
//     "SE210929",
//     "SE210403",
//     "SE211953",
//     "SE211914",
//     "SE211043",
//     "SE211927",
//     "SE210793",
//     "SE212030",
//     "SE210269",
//     "SE211059",
//     "SE211596",
//     "SE201170",
//     "SE200481",
//     "SE211528",
//     "SE201682",
//     "SE210474",
//     "SE201141",
//     "SE211901",
//     "SE211107",
//     "SE210496",
//     "SE203495",
//     "SE211615",
//     "SE212026",
//     "SE211932",
//     "SE204458",
//     "SE210041",
//     "SE210556",
//     "SE210768",
//     "SE211879",
//     "SE210380",
//     "SE204789",
//     "SE210166",
//     "SE210518",
// ];
// const lastSubmit = [
//     "https://drive.google.com/file/d/1ea4J4YXLj-w6DGAc7AJ4oxT8pO9WdaN1/view?usp=drivesdk",
//     "https://drive.google.com/file/d/1ev3IJDojvXbmHxKVY05kwuFDNdNp1NHp/view?usp=drivesdk",
//     "https://drive.google.com/file/d/1KhAPyZzCVtdls-AhhJR_HIhhq56x2c9Y/view?usp=drivesdk",
//     "https://drive.google.com/file/d/1cAD6_Y-PIk14atK79owpVUfKYmOAdY_W/view?usp=drivesdk",
//     "https://drive.google.com/file/d/1aLimgyfouBTR9nhxDWv6-SAGZlwM2Bq0/view?usp=drivesdk",
//     "https://drive.google.com/file/d/15qUmzRW3kU8lVZzpMbf0voo0eeB6XKUE/view?usp=drivesdk",
//     "https://drive.google.com/file/d/15F_FOpLC2qkJN_UYf26DmWi9nS3ELH-K/view?usp=drivesdk",
//     "https://drive.google.com/file/d/1QpGAX_JiObqeQuOWkpxEnXI1YeDCTStD/view?usp=drivesdk",
//     "https://drive.google.com/file/d/1QdJy0gZJ56Gep_CuYCT2Lw1pO90DZQJa/view?usp=drivesdk",
//     "https://drive.google.com/file/d/1na6YXyY-g2iisP0jaLuJ-V4nPY6-zx-8/view?usp=drivesdk",
//     "https://drive.google.com/file/d/1adUIOR06sS0sOMqiEI1ld8Wwc52iq86t/view?usp=drivesdk",
//     "https://drive.google.com/file/d/1rlsXr0qNzKP4ykrhTEc6Dk0JCSyt0qJX/view?usp=drivesdk",
//     "https://drive.google.com/file/d/1yeGtFbv0nIYhjfIVJ9BN_EtWwcnGSaKc/view?usp=drivesdk",
//     "https://drive.google.com/file/d/1Vezz7RvbGQplwymD76uxV5wtsg1LeltX/view?usp=drivesdk",
//     "https://drive.google.com/file/d/11pLDDVOU4Pkw41rfooxMZVT9Totqz1-V/view?usp=drivesdk",
//     "https://drive.google.com/file/d/1sqFH20iT7ZVGs9jqU4enN6CvEGGqLQw1/view?usp=drivesdk",
//     "https://drive.google.com/file/d/1gOKOo0dXsGpJM9rIouULOV_pjssuyn15/view?usp=drivesdk",
//     "https://drive.google.com/file/d/1XTJKX-mC0pjGxflfxI1Y94ZORgz9_8s5/view?usp=drivesdk",
//     "https://drive.google.com/file/d/1VAszJF6Xuex4LUIuroNYVLRZmm_r0Mrb/view?usp=drivesdk",
//     "https://drive.google.com/file/d/1ATHF2xDBxvutomeYKyi27wsPp6jpUrLN/view?usp=drivesdk",
//     "https://drive.google.com/file/d/1hHbkS6Vp7MSQuTTeH-MBCvltJY9eXhKg/view?usp=drivesdk",
//     "https://drive.google.com/file/d/1ijkuGvUDXxuMJ5QFCQYRrfxnezGQFJL2/view?usp=drivesdk",
//     "https://drive.google.com/file/d/1NWeQXvY-dQ2514xw4slMETrGUXdpb7Fv/view?usp=drivesdk",
//     "https://drive.google.com/file/d/16Gp8_IvWc0SVomj8uqLrxA6MMj04Q_R_/view?usp=drivesdk",
//     "https://drive.google.com/file/d/1Oe7kSkrnVveM97zK8Q5iNREHxP5Sw6bI/view?usp=drivesdk",
//     "https://drive.google.com/file/d/1ZPtHhnA7ooq4y1M29XwbEcx6ApvpQYd5/view?usp=drivesdk",
//     "https://drive.google.com/file/d/1Mzhk9WFSrnHTGDRXU4hOdNPsHMJSNa4T/view?usp=drivesdk",
//     "https://drive.google.com/file/d/1hAK-HJFhHyJ_iVLUBd15D-IIiNBo1rK1/view?usp=drivesdk",
//     "https://drive.google.com/file/d/1RGbUzbKMfCc6kp40K6NUj8aM2RcDh16s/view?usp=drivesdk",
//     "https://drive.google.com/file/d/1SGkB4xaNfbW1GBelpdhrb-AdGuIwBYFF/view?usp=drivesdk",
//     "https://drive.google.com/file/d/1ox6G8M-tSlG5qhYiaNz7ykt7OkA3BiGd/view?usp=drivesdk",
//     "https://drive.google.com/file/d/1PJ7drdDC7Wa1wXB1JAf76xKWjDsEORf_/view?usp=drivesdk",
//     "https://drive.google.com/file/d/1hBfPxdVqHUmW1L5rGAK2A2CQVLaIn5MS/view?usp=drivesdk",
//     "https://drive.google.com/file/d/1upnTYTlqOVR9tqoXMy74dPzBlenki-sx/view?usp=drivesdk",
//     "https://drive.google.com/file/d/1jwvUy7VTbquzja9y6TMOGZtwZx4ZKndF/view?usp=drivesdk",
//     "https://drive.google.com/file/d/1QhzLZRKV2swEoRWUJMOrS6KGYW8FJ8eF/view?usp=drivesdk",
//     "https://drive.google.com/file/d/10xuRcjtE2M6UjGsiN1LX8a1_MRmU_FTu/view?usp=drivesdk",
//     "https://drive.google.com/file/d/1gtQyfbmqs5hH-DNYcnRlesqZfVxfCImY/view?usp=drivesdk",
//     "https://drive.google.com/file/d/1BoS_A5oplcgaWEvAbZHHMp5dn2YzzS0k/view?usp=drivesdk",
//     "https://drive.google.com/file/d/1Zz5FTBmr8dGbzRRTOwjRch4711e6Zvpa/view?usp=drivesdk",
//     "https://drive.google.com/file/d/124iFNFeoTAk0S425w-tplah6arqYLNhL/view?usp=drivesdk",
//     "https://drive.google.com/file/d/12A53IB8gmFx1Qv5aR-pZZ0dWwwT1ppai/view?usp=drivesdk",
//     "https://drive.google.com/file/d/1U2xQ9b6LAkfeEQv6rmswRO2DgliPjSHl/view?usp=drivesdk",
//     "https://drive.google.com/file/d/1bAWTnacu2TcLq3O6I_kMgwyEEEtZ453D/view?usp=drivesdk",
//     "https://drive.google.com/file/d/1a6aOl_DCEFJKwyr6JPGYFjCknp9T7EHH/view?usp=drivesdk",
//     "https://drive.google.com/file/d/1z6M2xpLsHrwKhqNw4cEoYZ14X3Ec1xBg/view?usp=drivesdk",
//     "https://drive.google.com/file/d/1Li1mtFSyQjHy2l6SOcnu8DBdOE4L_s9O/view?usp=drivesdk",
//     "https://drive.google.com/file/d/1jjdEm8XXQOyx-Sk9hqRlT0e2s2MWPtPR/view?usp=drivesdk",
//     "https://drive.google.com/file/d/1d839MEK4LDJ0uJn7OD8iXwfdLwQzcf0_/view?usp=drivesdk",
//     "https://drive.google.com/file/d/1g09V4PDTSRn7OztotVrjuCVdI6WBk4Ea/view?usp=drivesdk",
//     "https://drive.google.com/file/d/1QEOWvRrZUlQDqMUJpnQKdLS3zZWa_234/view?usp=drivesdk",
//     "https://drive.google.com/file/d/1hC6S1Ya0_6NKWIzq8msWZCAdChNArlq6/view?usp=drivesdk",
//     "https://drive.google.com/file/d/1IJQW-A3oyiAa52ZjjvI_SG313rQND3Oq/view?usp=drivesdk",
//     "https://drive.google.com/file/d/1m7TTKeLA7L5S5EdLQ-UAASolgLTzxp0q/view?usp=drivesdk",
//     "https://drive.google.com/file/d/1objCekiSy-ap5oqe7CXcAg_DXjRuYq3l/view?usp=drivesdk",
//     "https://drive.google.com/file/d/1aiIFKwgTu3ollVQVwF6ws9rSARyRCEkH/view?usp=drivesdk",
//     "https://drive.google.com/file/d/1BHpa1b1_wg8pAoQPOf3R5rpu_mi43ego/view?usp=drivesdk",
//     "https://drive.google.com/file/d/1EyZRjy3oQhIX-VIRaiGy_uGzFZCWj4kK/view?usp=drivesdk",
//     "https://drive.google.com/file/d/1eFPCGzhELNCX86tmYhB5gpsrQ-gfqcoE/view?usp=drivesdk",
//     "https://drive.google.com/file/d/14kpzT6Nh1PdpHp30yXdGKhp7gZILWj7g/view?usp=drivesdk",
//     "https://drive.google.com/file/d/1lLeLaIYIi9RRZPyRiglpH65yb0z_9665/view?usp=drivesdk",
//     "https://drive.google.com/file/d/171b7j5DWunbSkK9yG4XQopxQf14V8N1f/view?usp=drivesdk",
//     "https://drive.google.com/file/d/1tIDPbqxy1ULmHYA3xSQ5YNs8NIvoEs3z/view?usp=drivesdk",
//     "https://drive.google.com/file/d/1ABfgrkBUqDrWyVzj3aqSVZ8st6f1K-NQ/view?usp=drivesdk",
//     "https://drive.google.com/file/d/1RBe1bMWXCankS4kcs61sABFVuY7oA7py/view?usp=drivesdk",
//     "https://drive.google.com/file/d/1Dv2oFRqa9a5756a7p3PftNXYnm4WmFvf/view?usp=drivesdk",
//     "https://drive.google.com/file/d/1WCIVAyhDcqhaKWQygPNPsQ1LPDWwVTYj/view?usp=drivesdk",
//     "https://drive.google.com/file/d/1sUggFwQNST8OvZrT9ZOcXAYIYIrKcLW4/view?usp=drivesdk",
//     "https://drive.google.com/file/d/1vTd0kbgsQYHJLGdOoOIXEL3Z6E59EVth/view?usp=drivesdk",
//     "https://drive.google.com/file/d/1N5ntwtw4kh5Zx7uvPmOZlw3sjaplCaFf/view?usp=drivesdk",
//     "https://drive.google.com/file/d/1AT8KKNpikZoEoyZryGBnNEjuz0I-Gshw/view?usp=drivesdk",
//     "https://drive.google.com/file/d/11ieDInC9nrjGitd-5wPnwDeY3RKDh92N/view?usp=drivesdk",
//     "https://drive.google.com/file/d/1jjk8cp-CgVw6DnR6I4VRv6W_kD-kK6w2/view?usp=drivesdk",
//     "https://drive.google.com/file/d/1nSswKhQNJokAb1iTb5mbPQ6wMN_oqHcX/view?usp=drivesdk",
//     "https://drive.google.com/file/d/1_r6wwZsqKeudYe3bdOOM7PqU2R9nxZ_L/view?usp=drivesdk",
//     "https://drive.google.com/file/d/1SQvF2l7xSMAfSW9IOnKygCK1ca1se71y/view?usp=drivesdk",
//     "https://drive.google.com/file/d/1XdysXmQHxWWb6d5jlTRBf6N_zdc9FYco/view?usp=drivesdk",
//     "https://drive.google.com/file/d/1CnoXZCCWDqysJa_8YUHAfka7i3Hw6qDq/view?usp=drivesdk",
//     "https://drive.google.com/file/d/1ITDOvxRwKKGPXWNoHKCNClOrWk4bJcXZ/view?usp=drivesdk",
//     "https://drive.google.com/file/d/1fAVvkxmGj1XVt7z9vHIgd9HRczQZkSzO/view?usp=drivesdk",
//     "https://drive.google.com/file/d/1L0MwxD1mAsLx0RUoz805ssaKoTYb8VTq/view?usp=drivesdk",
//     "https://drive.google.com/file/d/13FKbPCpUSRrAbhfIuSjLlK_wRC39Sr1N/view?usp=drivesdk",
//     "https://drive.google.com/file/d/10Av0onoRCUdgb-UDG-1dKGy0wj1ZrzHQ/view?usp=drivesdk",
//     "https://drive.google.com/file/d/1yhC6GJCSNvLYq1keD3F-lgiBGHl-DlMI/view?usp=drivesdk",
//     "https://drive.google.com/file/d/1f-OIVktKeM-nYDkKu8BTelv_to6eRqUF/view?usp=drivesdk",
//     "https://drive.google.com/file/d/1ziAeBXxaVdrF59b5qbTh61l9sjIshlyy/view?usp=drivesdk",
//     "https://drive.google.com/file/d/16SwY0kd6i_n5w-Ie8g8VY_JG3wYcLms-/view?usp=drivesdk",
//     "https://drive.google.com/file/d/1DGSXFSp5VQYRaFhx4-QETqiBrf4X2t4L/view?usp=drivesdk",
//     "https://drive.google.com/file/d/1k45YcgRsg8TVN2f2IvY-Ial4WQVN6RVB/view?usp=drivesdk",
//     "https://drive.google.com/file/d/1_hSLoGooxGAk2RbpxM7qP3NNOhSTznJz/view?usp=drivesdk",
//     "https://drive.google.com/file/d/1AW0t8RB8emFCbbpnUuOCEKMZ-eHEvIas/view?usp=drivesdk",
//     "https://drive.google.com/file/d/1lnPzdloxvA-G_Ul6xQYkCFP_IUQoc50b/view?usp=drivesdk",
//     "https://drive.google.com/file/d/1e5ZUGTb1vZmQTYY1Jlk_nlYzgszWYRke/view?usp=drivesdk",
//     "https://drive.google.com/file/d/1p4xwU8dyFbGzuWCdJSuUh40lkVWFoKgM/view?usp=drivesdk",
//     "https://drive.google.com/file/d/1JDokEW1Xkvpcg9iC7kJ-BUnwCB4iMsMb/view?usp=drivesdk",
//     "https://drive.google.com/file/d/1vUIrtlWMNMRVqEyJHMwfzOEBW5hRim1e/view?usp=drivesdk",
//     "https://drive.google.com/file/d/1akhXlJ_iksngsIlpxstKvgW-ZYvj7rKa/view?usp=drivesdk",
//     "https://drive.google.com/file/d/1kHSmC345cQ4CwqNVDn5bCqhv7R4xFFRf/view?usp=drivesdk",
// ];
// export const submit = async (req: Request<ParamsDictionary, any, any>, res: Response, next: NextFunction) => {
//     for (let student of studentCodes.keys()) {
//         const candidate = await prisma.candidate.findUnique({
//             where: {
//                 studentCode: studentCodes[student],
//             },
//         });

//         if (candidate) {
//             await prisma.scoreResult.update({
//                 where: {
//                     candidateId: candidate.id,
//                 },
//                 data: {
//                     firstSubmit: firstSubmit[student],
//                     finalSubmit: lastSubmit[student],
//                 },
//             });
//         }
//     }
// };
